slackapi/hubot-slack

index.coffee
package.json
src/listener.coffee
src/message.coffee
src/slack.coffee
test/message.coffee
test/slack.coffee
test/stubs.coffee

Regular text messages now use a TextMessage subclass called
SlackTextMessage, which includes both the parsed text (as `text`) and
the unparsed text (as `rawText`).
Other messages that used to be ignored are now received as either
SlackRawMessage or SlackBotMessage. These do not descend from
TextMessage so they won't be seen by normal `hear` or `respond`
listeners.
A few new Listener classes were created, SlackRawListener and
SlackBotListener, to make it slightly easier to write code tailored for
these new message types.
This PR is based on #131.

Create new Message types for slack messages

---

src/slack.coffee

I could not read error's detail, because it is using `toString()`.
```
[Sun Jan 11 2015 16:51:34 GMT+0900 (JST)] ERROR Received error [object Object]
```
use JSON.stringify to print error object.
```
[Sun Jan 11 2015 16:59:42 GMT+0900 (JST)] ERROR Received error {"code":-1,"msg":"slow down, too many messages..."}
```

use JSON.stringify to print Error object

---

src/slack.coffee

The `hubot-slack@3.2.1` has crashed by sending an empty message. See commit.
Script:
```
module.exports = (robot) ->
robot.respond /hello/, (res) ->
res.send '' # empty string
```
Log:
```
[Tue Feb 17 2015 21:17:04 GMT+0900 (JST)] ERROR Received error [object Object]
[Tue Feb 17 2015 21:17:04 GMT+0900 (JST)] ERROR undefined
[Tue Feb 17 2015 21:17:04 GMT+0900 (JST)] ERROR Exiting in 1 second
```
API response: 
```
{ code: 2, msg: 'message text is missing' }
```

ignore empty message

---

package.json
src/slack.coffee

This pull request reimplements slack attachment support in Hubot.
It does so using an as-yet undocumented Slack API, where chat.postMessage will now accept an `as_user` boolean argument. Even though this API has been deployed to our production servers, **_it should be considered provisional and the details may change_**. We'll be documenting it on api.slack.com and confirm here when we're confident that the design is right.
I believe this is compatible with both scripts that used hubot-slack v2's attachment support, and scripts that use @inkel's [hubot-slack-attachment](inkel/hubot-slack-attachment) script. But, I don't have many test cases, so I may have missed something.
I'm looking for feedback on whether this approach makes sense, and bug reports where the attachment support doesn't …

Add back support for Slack attachments

---

src/slack.coffee

When attempting to emit slack.attachment from a router response in our hubot, I saw the dreaded `ReferenceError: robot is not defined` error in the logs. I updated the customMessage function to check the passed username with `@robot.name` rather than `robot.name`.
Then I noticed by passed name wasn't working (was showing up as 'Bot'). Fixed that too. :wink:
Works great now! Thanks for adding support for attachments back into the adapter!

Fixes to slack.attachment support

---

README.md

The current language around removing the old hubot integration implies that you can actually delete the integration, which is confusing. I went searching all over for a way to "delete" or "remove" him, since all I could find in the UI was an option to "disable". Eventually I discovered #147 which clarifies that you cannot actually delete or remove old integrations, only disable. So updating the language in the README here would be helpful. :sparkles:

Copy edit for README

---

src/slack.coffee

Some bots should talk like people.

Allow use with a non-bot api token

---

src/slack.coffee
test/slack.coffee
test/stubs.coffee

This change uses the new callbacks available in node-slack-client. If
robot.send is called like:
robot.send {room: 'someuser'}, 'message'
If someuser is a user and there is no existing DM, it will use openDM to
establish a new private message with the user and send the message in the
callback.

Allow sending DMs to arbitrary users

---

src/slack.coffee

No longer exit on client close

---

src/slack.coffee

I've been having problems with hubot crashing periodically, usually overnight when no one is activel. I found errors in the log like:
```
TypeError: Cannot read property 'email' of undefined
at SlackBot.userChange (node_modules/hubot-slack/src/slack.coffee:79:7, <js>:113:36)
at SlackBot.__bind [as userChange] (node_modules/hubot-slack/src/slack.coffee:1:1, <js>:3:61)
at SlackBot.loggedIn (node_modules/hubot-slack/src/slack.coffee:64:7, <js>:83:28)
at Client.__bind (node_modules/hubot-slack/src/slack.coffee:1:1, <js>:3:61)
at Client.EventEmitter.emit (events.js:96:17)
at Client._onLogin (node_modules/hubot-slack/node_modules/slack-client/src/client.js:100:14)
at __bind (node_modules/hubot-slack/node_modules/slack-client/src/client.js:2:59)
at …
```

Guard against real-time messaging API returning empty users

---

README.md

- `heroku addons:add` has been deprecated and replaced with `heroku addons:create`
- Heroku will now automatically spin up a free dyno when you deploy so it's no longer necessary to launch one manually

Update README to reflect Heroku changes

---

src/slack.coffee

When using `msg.reply`, users would have to have their Slack nickname as a highlight word to receive notifications, because Hubot wasn't sending the special formatting to generate an @-reply. This fixes it so that Hubot generates correct @-replies.
Fixes #167.

Correctly @-mention users when using msg.reply

---

src/slack.coffee
test/slack.coffee

`@here` is added to the notification method of Slack.
https://slack.zendesk.com/hc/en-us/articles/202009646-Making-announcements

Add a notice to @here.

---

src/slack.coffee

I'm debugging an error I received overnight that crashed my hubot instance over at https://github.com/github/hubot-slack/pull/1 . Digging into it a bit more, I found that the adapter's error handler is exiting when the error happens.
This PR updates the adapter to not exit, and to use [hubot's error handling](https://hubot.github.com/docs/scripting/#error-handling) instead of logging it (the error handling logs by default).

robot.emit 'error' for slack client errors

---

src/slack.coffee

I wanted access to more details about a user in order to write [listener middleware](https://hubot.github.com/docs/scripting/#listener-middleware) for doing things like blocking access for restricted and bot users.
The data is there in hubot-slack, but just not put into hubot's brain. I had considered just adding everything to the user object at the top level, but I think it'd be better to namespace it under `slack`, so it doesn't seem like that's something a script author should be manipulating.
Here's what it looks like slackbot looks like:
```
{ id: 'USLACKBOT',
name: 'slackbot',
real_name: 'slackbot',
email_address: '',
slack: 
{ id: 'USLACKBOT',
name: 'slackbot',
deleted: false,
status: null,
color: '757575',
real_name: 'slackbot',
tz: null,
tz_label: 'Pacific Daylight Time', …
```

Persist more user data from Slack in the brain

---

src/slack.coffee

Since Slack client seems to have troubles reconnecting occasionally (e.g. slackhq/hubot-slack#203), this seems like the only way to solve it right now. I'm running Hubot using supervisor and in the case of Slack client dropping its connection it seems to me that having the Hubot process exit and get restarted from e.g. supervisor is the way to go.

If Slack client closes, exit the hubot process

---

README.md

Removed the `npm install hubot-slack step`.  If you change the adapter from the default configuration ('campfire') during `yo hubot` interactive setup (or with the --adapter=slack flag), the hubot-slack module will be installed for you as the final dependency.  Using npm to install it again is redundant.

Updated README.md initialization steps

---

src/bot.coffee
test/bot.coffee
test/stubs.coffee

Fixes a bug whereby messages with a bot user instead of a regular user hosed poor Hubot. Also, rolls message type `bot_message` in with `message`, as originally intended.
Fixes #323
Added tests around bot messages.

Handle bot message

---

src/formatter.coffee
test/formatter.coffee
test/stubs.coffee

Prior to this change: a period or hyphen would cause this code to
only match the username before one of these unexpected characters.
This notifies the wrong person.
The logs would show:
DEBUG Sending to stackstorm: <@XXXXXXXXX>.welborn: host responded to ping.
Instead of:
DEBUG Sending to stackstorm: <@XXXXXXXXX>: host responded to ping.
When sending:
@john.welborn: host responded to ping.
Other special characters are not allowed.
From the slack ui when changing username:
"Usernames must be all lowercase. They cannot be longer than 21 characters and
can only contain letters, numbers, periods, hyphens, and underscores."

Support slack usernames with all allowed characters

---

src/bot.coffee
src/client.coffee
test/bot.coffee
test/stubs.coffee

> Default all messages to `as_user = true`. Also ignore all messages we send.
> Fixes #336
> Wrote tests to ensure that as_user is being set to a default value, and that that default value can be overridden.
In the course of writing this, I realized that bots do not ignore messages they themselves sent. This becomes apparent with the new functionality especially, so I've rolled logic for that (and tests!) into this PR as well.

Default as user true

---

src/client.coffee
test/client.coffee
test/stubs.coffee

Previous to hubot-slack 4.0.0, `robot.messageRoom` would accept room names.  This PR translates room names to room ids, in order to improve compatibility with existing hubot scripts.
Write a hubot script that sends a message to a room by name, e.g.:
```coffeescript
module.exports = (robot) ->
robot.respond /test messageRoom/, (msg) ->
room = 'general'
robot.messageRoom room, 'hi there!'
```
This will not work with hubot-slack 4.0.2.

Accept room names for robot.messageRoom

---

src/client.coffee

This was brought to my attention offline
> Without this change, any plugin written for hubot would be *required* to be aware of slack, as it would be *required* to look up the channel ID in any circumstances except replying to a message.
> This means that most "generic" plugins (for example, hubot-notify) would have to be re-written to be specific to slack - something that goes against the freedoms of having these plugins etc within hubot.
N/A
Existing tests

Adding back channel lookup for non-slack plugins

---

src/bot.coffee
src/client.coffee
test/bot.coffee
test/client.coffee
test/stubs.coffee

> Now you can pass in user objects as message envelopes.
> Fixes #332
> Added tests around passing in user names (prepended with "@") and user objects

Fixes #332 by allowing user objects to be envelopes

---

package.json
src/bot.coffee
test/bot.coffee
test/stubs.coffee

Add hubot.Robot.react
Per #360, this implements `robot.react` as a replacement for the approach from [mbland/hubot-slack-reaction-example v1.1.0](https://github.com/mbland/hubot-slack-reaction-example/blob/v1.1.0/scripts/handle-reaction.coffee). Specifically, the `ReactionMessage` definition will no longer be required in client code, and this:
```coffeescript
robot.listen(
(message) -> message instanceof ReactionMessage
handleReaction
)
```
can now become:
```coffeescript
robot.react handleReaction
```
`Robot.react` can also take optional  `matcher` and `options` arguments just like the underlying `Robot.listen` method:
```coffeescript
robot.react(
(message) -> message.type == 'added' && message.reaction == '+1'
{id: 'my-reaction-matcher'}
handleReaction
)
```
__NOTE:__ It was necessary …

Add hubot.Robot.react

---

package.json
src/bot.coffee
test/bot.coffee

So, it turns out that the `robot` base class has an event handler named `topic`, and the `bot` derived class overrides that into a different method signature, and this breaks things.
https://dev4slack.slack.com/archives/sdk-hubot-slack/p1478282324000005 and _ff._

Renaming a function that has a name collision with the base class

---

src/formatter.coffee
test/formatter.coffee

> The formatter was producing links for channels and usernames with preceeding @ and #. Also added support for parsing subteam links and future proofed for other link types that are currently unknown
> e.g. Fixes #288 and closes #366 
> Modify channel and user name tests to change the expected output where appropriate (that is, always ensure channels are proceeded by # and usernames are proceeded by @)
> Added tests for subteam links
> Added tests for parsing unknown link types

Improve the SlackFormatter to add support for subteams and fix inconsistencies

---

src/bot.coffee
test/bot.coffee
test/stubs.coffee

Store users in the robot.brain.users. PR is written with reference to [old code](https://github.com/slackapi/hubot-slack/blob/1c49569b52b7774e07e158f4909b3a8e3a3a72c2/src/slack.coffee#L67).
Fix #352
~~Not yet.~~
Call `userChange` and `loadUsers`, after compare input data with data which in brain.

Load users to robot.brain.users

---

ISSUE_TEMPLATE.md

Those links are currently broken, see here for example: https://github.com/slackapi/hubot-slack/issues/393
Merge this and hopefully the next issue has working links.

Fix CoC and Contribution guideline links on issues

---

src/bot.coffee
test/bot.coffee

enhances SlackBot.userChange() to take either a user or event

---

src/bot.coffee
src/client.coffee
src/slack-message.coffee
test/bot.coffee

Prior to 900402ea254b0fdf5a819fd3073325c68f1692a9, hubot-slack returned a message object which included the raw text from the Slack API along with the raw Slack Message object. This was useful for middleware and scripts which reformatted Slack text in different ways than hubot-slack's own default formatter. This object was a subclass of hubot's `TextMessage` which was otherwise compatible.
For example, a middleware might try to detect URLs that were autoexpanded by the Slack API and restore them to their original format; this is only possible if the raw text is included so the unparsed URLs can be read.
#181 also discusses using this property (at the time when it still existed).
Added a test to the `SlackBot.message` code.

Return rawText and rawMessage objects

---

src/bot.coffee
src/client.coffee

Currently the hubot slack adapter makes a call to users.list everytime we call robot.brain.set  since that fires the 'loaded' event. If a call updates several properties separately then you get multiple calls to the slack api to load users.
For #419
Currently this is manually tested and after a couple of hours of trying to figure out the test framework I had to cut my losses. If someone else can write a test for this or can help me write a test that would be appreciated. Used to using sinon where I can clearly see the calls made to functions.

Initial fix

---

docs/_pages/advanced_usage.md
slack.coffee
src/client.coffee
test/stubs.coffee

fixes #421 
there aren't any tests here because it would require building a new test harness capable of launching a child process for hubot with predefined environment variables. that seems too expensive for now.

setup env vars for RtmClient and rtm.start options

---

CONTRIBUTING.md

While reading the contribution guidelines for preparing another MR I noticed a typo. 
So I said to myself, let's start small and fix that instead :)
-
Reading the doc

Fix for typo: remove duplicate 'about' from contributing.md

---

src/message.coffee

Fixes an incorrectly merged community contribution that wasn't using the correct bot name.

Fix bug using robot's name for prepending

---

src/bot.coffee
src/client.coffee
src/message.coffee
test/bot.coffee
test/client.coffee
test/stubs.coffee

Do some work to standardize the structure of a user inside of the adapter. Modify `loadUsers()` to fetch a Slack user from a bot id. Addresses #414 and #427.

Return Hubot Users

---

src/bot.coffee
src/client.coffee
src/message.coffee
test/client.coffee
test/stubs.coffee

#465 introduced new calls to the Web API that were being incorrectly called and used, as noted in #468. This fixes the usage of the calls.

Fix Slack API Calls

---

src/extensions.coffee

this caused `PresenceMessage` to throw inside the adapter. fixed here and tested using example in #478

fixes issue with presencemessage missing

---

src/client.coffee
src/extensions.coffee
test/bot.coffee
test/stubs.coffee

and preserves former as an alias, fixes #455
Describe the goal of this PR. Mention any related Issue numbers.

renames Robot.react to Robot.hearReaction

---

docs/_pages/basic_usage.md

This is just a simple typo fix in one of the comments of the examples.

Fix typo in presence example

---

package.json
src/client.coffee
test/client.coffee
test/stubs.coffee

Add a local mapping for bot user ID to user representation to reduce dependency on `bots.info` and `users.info` calls.
Fetch event `user` and `item_user` from the brain if possible - if not, use `users.info`

Decrease Web API Dependencies

---

package.json
src/bot.coffee
src/client.coffee
src/message.coffee
test/bot.coffee
test/client.coffee
test/message.coffee
test/stubs.coffee

Adds a basic cache for conversations and uses user representation in brain for mentions.
Now, conversations will only update if the stored information is older than 5 minutes. This means removing the logic of conversations in `client.coffee` and adding some basic logic into `message.coffee`. This will ensure mostly accurate conversation representations, but decrease the possibility of accidental rate limiting and unnecessary calls to conversations.info.

Update conversations.info calls to Web API

---

src/message.coffee
test/message.coffee

there was an issue with the coffeescript syntax that resulted in `a` being treated as a function. this change fixes that.
fixes #500

Fix attachment flattening inside buildText

---

src/bot.coffee
src/client.coffee
test/bot.coffee
test/client.coffee

There was an issue where a user representation would have nested `slack` objects inside of them. This prevents that from happening and moves all calls to `@updateUserInBrain` to `client.coffee`.

Fix User Object duplication

---

src/client.coffee

If a bot user has no association to a user id, make sure it's still defined.

Fix unassociated bot user

---

src/bot.coffee
src/client.coffee
test/bot.coffee

swaps out rtm message subtypes for discreet messages for enter and leave

---

docs/_pages/basic_usage.md
src/message.coffee

add properties of ReactionMessage to docs

---

src/client.coffee
test/client.coffee
test/stubs.coffee

fixes #519
Specifically when /remind is setup to trigger a hubot event
Prevent `bot_not_found` when looking up SlackBot using `bots.info` with id:B01 from causing an error that stops execution of listeners

One way to fix bot_not_found due to SlackBot

---

package.json

This upgrades to the latest lodash; the version in `package.json` was a major release behind. The tests pass with this new version.

Upgrade lodash to the latest

---

.travis.yml
package.json

updates to the latest v3.x @slack/client

---

.travis.yml
package.json
test/bot.coffee

This fixes running the tests with Hubot 3.x.
I was seeing these four `instanceof` tests fail. I believe the reason for this is that Hubot 3.x is written in JavaScript using ES2015 classes, and there's a subtle issue with `instanceof` not playing nicely when CoffeeScript classes enter the picture.

Fix tests on new hubot

---

package.json
src/extensions.coffee
test/bot.coffee

Hubot `v3.0.0` updated the source to `es2015`, which includes implementing a coffeescript-compatible wrapper to not break adapters. However, this meant that we were adding our extensions (`hearReaction` and `presenceChange`) to the coffeescript wrapper rather than the `Robot` prototype. This fixes that by checking `robot.name` (which is `CoffeeScriptCompatibleClass` for Hubot `v3.0.0` or higher) and importing the proper hubot based on that.
Fixes #538 and #537

Imports Hubot prototype dynamically for extensions

---

package.json

This updates the dev dependencies just enough to get a clean `npm
audit`.
mocha and codecov dev dependencies are out of date, resulting in scary warnings from recent versions of npm. This fixes those issues.

update dev dependencies

---

src/client.coffee

This PR adds configurability to the time Hubot will consider the data returned from `conversations.info` "fresh", without fetching it once again. This allows users to address concerns such as the on raised in #554.

allows users to configure the TTL of conversation info data

---

src/client.coffee

In #560, we failed to convert the value from a string to a number, so that it could be used as the TTL. This PR fixes that problem.

fix issue with using a string from env vars as a number

---

.vscode/launch.json
package.json

This option has been deprecated, but a simple `--require` will do the job just as well. See:
https://github.com/mochajs/mocha/wiki/compilers-deprecation

Remove deprecated mocha --compilers option

---

src/bot.coffee

As described in #536, hubot-slack sometimes appears to disconnect and never come back. There is a [`disconnect` event](https://github.com/slackapi/node-slack-sdk/blob/13248f403758d7158c1bafe5db009e3f0416b4b8/lib/clients/events/client.js#L26-L27) which occurs specifically when the RTM client has disconnected and will not try again; this is currently not handled by the codebase, so that would explain why what we're seeing is going uncaught. In this PR, I've added a new handler for that method; right now I'm having that close the bot entirely, allowing the running process manager to clean up and restart Hubot.

Bot: catch and react to disconnection event

---

src/client.coffee

This pull request fixes #586 by changing the internals of `SlackClient` a bit.
The latest RTM event payloads from Slack has both `user` and `bot_id` even for events generated by a bot user as below:
```json
{
"bot_id": "B12345678",
"suppress_notification": false,
"type": "message",
"text": "Badgers? BADGERS? WE DON'T NEED NO STINKIN BADGERS",
"user": "U12345678",
"team": "T12345678",
"bot_profile": {
"id": "B12345678",
"deleted": false,
"name": "hubot",
"updated": 1568973776,
"app_id": "A12345678",
"icons": {
"image_36": "https://a.slack-edge.com/80588/img/services/hubot_36.png",
"image_48": "https://a.slack-edge.com/80588/img/services/hubot_48.png",
"image_72": "https://a.slack-edge.com/80588/img/services/hubot_72.png"
},
"team_id": "T12345678"
},
"source_team": "T12345678",
"user_team": …
```

Fix #586 hubot-slack calling bots.info a suspicious number of times

---

docs/_posts/2020-04-03-v4.7.2.md
package.json

* Bot: catch and react to disconnection event (#572) thanks @mistydemeo
* Fix #586 hubot-slack calling bots.info a suspicious number of times (#588) thanks @mistydemeo @seratch
@aoberoi @shaydewael @stevengill 
If someone can merge this PR and publish the npm package for me, that'd be appreciated.

Release v4.7.2

---

src/bot.coffee

This is a really minor syntax-only change and shouldn't affect behaviour at all.
Because what we're assigning in the happy side of this condition is the same as what we're checking in its expression we can use Coffeescript's shorthand with the existential operator, i.e. instead of
a = if b? then b else c
use this:
a = b ? c
Source: https://coffeescript.org/#existential-operator
Describe the goal of this PR. Mention any related Issue numbers.

Use Coffeescript conditional assignment shorthand

---

.travis.yml
src/bot.coffee
src/message.coffee

This PR continues https://github.com/slackapi/hubot-slack/pull/528 works.
Make sure the classes in this code work in Coffeescript 2 (and with hubot 3).
A few of the semantic differences between Coffeescript 1 classes and ES2015 classes has introduced some backwards compatibility issues, as follows:
[Breaking Changes From CoffeeScript 1.x to 2](https://coffeescript.org/#unsupported-get-set)
Known Issue: This PR doesn't make hubot-slack work with hubot 2 in Coffeescript 2. Because hubot 2 still based on Coffeescript 1.
Refs: https://github.com/slackapi/hubot-slack/issues/526

Add compatibility for Coffeescript 2 (and hubot 3)

---

.travis.yml
src/bot.coffee
src/message.coffee

Reverts slackapi/hubot-slack#565
Let me revert this change until we replace fat arrow methods.

Revert "Add compatibility for Coffeescript 2 (and hubot 3)"

---

src/bot.coffee
test/bot.coffee
test/stubs.coffee

Enter and leave messages don't have timestamps, unlike other events like text messages.  Hubot doesn't have a place for them e.g. for enter messages in the EnterMessage class, but Slack supports them and other actions regarding enter/leave events in Slack expect you to use a timestamp, so you need to be able to get it from somewhere.
This change works around the fact that they're not present in Hubot's classes by inserting a `ts` field after the message object has been created.  It includes tests to confirm that Slack's event timestamp is successfully passed on to Hubot.
Resolves #575

Add timestamps for enter and leave messages

---

src/bot.coffee
test/bot.coffee

Hubot cannot hear a reply message broadcasted to channel (sent with `Also send to #channel` checked).
Write following script:
```
module.exports = robot => {
robot.hear(/^test$/i, msg => console.log(msg.match));
}
```
1. When we send message `test` to a channel or thread, we can see `console.log` output as expected.
2. When we send message `test` to a thread with checking `Also send to #channel`, we also expect same log to be seen, but we cannot see the log.

Add support for thread_broadcast message

---

.github/maintainers_guide.md
docs/_posts/2021-01-26-v4.9.0.md
package.json

v4.9.0 is ready for release now.

version 4.9.0 release

---

.github/workflows/triage-issues.yml

Adds Github action to help stale and close inactive issues.

Add git stale action

---

slack.coffee

This pull request fixes #632 -- refer to the issue for the context

Fix #632 Change the default settings to "useRtmConnect: true"

---

src/bot.coffee

This pull request resolves #643

Fix #643 Resolve undefined user ID in debug logging
