slackapi/hubot-slack

- README.md
Added a section to clarify how to configure hubot scripts to notify specific channels.
> Add section for channel notifications

- README.md
Updated the link in the README to point to the config variables correctly.
> Corrected Configuration link in README

- README.md
> Remove Procfile edits in Readme

- src/slack.coffee
- test/slack.coffee
- test/stubs.coffee
Original work from @kdawgwilk in #193
Closes #132
> impr: add support for mentioning users in hubot messages

- src/slack.coffee
> support channel_id in addition to channel_name in `send` and `customMessage`

- README.md
> change build badge to svg

- package.json
- src/bot.coffee
- src/client.coffee
- test/bot.coffee
- test/formatter.coffee
- test/stubs.coffee
@johnagan for your perusal.
- Broke existing tests apart for SlackBot and Formatter
- Removed message splitting tests, as I understand we are removing that functionality?
- Reworked stubs to actually work
- Added some logic to sending messages so that empty messages aren't sent (per existing tests read as a spec for functionality)
> V3 sdk updates writing tests

- package.json
Stuff that should _not_ have been pushed with the recent documentation update.
> And some things that should not have been forgotten were lost.

- docs/_pages/basic_usage.md
- docs/_pages/upgrading.md
Restores the upgrading documentation that got nuked with the recent documentation upgrade.
> Restore the original upgrading docs so they can be added to

- docs/index.md
> Fixes typos, finishes an incomplete sentence (I took some creative liberties in extrapolating the meaning of the incomplete sentence.  I hope it fits your vision!)
> Fix typos, finish sentence

- docs/_pages/auth.md
* [ X] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [ X] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [X ] I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* [X ] I've written tests to cover the new code and functionality included in this PR.
* [X ] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://docs.google.com/a/slack-corp.com/forms/d/1q_w8rlJG_x_xJOoSUMNl7R35rkpA7N6pUkKhfHHMD9c/viewform).
Fix duplicated sentence in docs -> auth.md
> Remove duplicated sentence

- src/bot.coffee
- test/bot.coffee
- test/stubs.coffee
> check for existence of `user.profile` before reading `email` from it.
> fixes #388
> added a new user stub without a profile and exercised the behavior using it.
> Fix users in brain when user doesn't have a profile

- docs/_pages/basic_usage.md
- src/bot.coffee
- src/client.coffee
> Adds support for bots to reply requests originating in a thread
> e.g. Fixes #393
> Add support for replying to threaded messages

- docs/_posts/2017-01-09-v4.3.3.md
- package.json
> Version number and changelog updates
> Release v4.3.3

- docs/_posts/2017-02-15-v4.3.2.md
> add missing changelog post

- docs/_pages/basic_usage.md
> Fix documentation sample

- docs/_pages/advanced_usage.md
> typo in env var example

- src/bot.coffee
- src/client.coffee
- test/bot.coffee
- test/client.coffee
- test/stubs.coffee
this should help solve issues related to timeouts on very large (enterprise) teams. this is work that will help #448
> implements pagination for users.list web api calls

- src/bot.coffee
- test/bot.coffee
See: https://github.com/hubotio/hubot/issues/1356
> Accept DM'ed commands with or without bot name prefix

- src/bot.coffee
Use `updateUserInBrain()` instead of `userForId()` to guarantee we're not putting incorrectly-structured data into the brain
> Use updateUserInBrain() to guarantee correct user structure

- src/client.coffee
> Fix undefined brain

- package.json
> updates @slack/client dep to version patched for security issue

- docs/_posts/2018-06-14-v4.5.2.md
- package.json
> Release v4.5.2

- src/message.coffee
- test/message.coffee
> improves checking for existence of strings before concatenation

- src/client.coffee
this will negatively impact perceived performance, but it is the only way to ensure that messages are output in order. for those who are concerned with the latency between for messages sent from multiple calls to `res.send()`, the advice should be to batch those messages into a single message, potentially with attachments or new line characters.
fixes #379
> force sent messages to be in order by limiting concurrency

- .travis.yml
> adds node v10 to travis test matrix

- docs/_pages/advanced_usage.md
> add documentation about using a proxy

- src/bot.coffee
Resolves #523
* [x ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
> Change isLoaded to brainIsLoaded if disableUserSync if set

- docs/_config.yml
- docs/_includes/head.html
- docs/_includes/page_header.html
- docs/_includes/side_nav.html
- docs/_includes/tag_manager.html
- docs/_layouts/default.html
- docs/styles/docs.css
Updates styling to the new branding - includes fonts, favicons, and colors. Decreases the amount of CSS dependencies we have as well.
Also adds a script for Google Tag Manager
> Update documentation styling

- docs/_posts/2019-04-29-v4.7.0.md
- package.json
> Release v4.7.0

- docs/_posts/2019-04-30-v4.7.1.md
- package.json
> Release v4.7.1

- .travis.yml
It's not urgent at all but this pull request adds Node.js 12 to the CI builds. It seems we can get rid of very old versions but we can do it separately.
> Add Node 12 to TravisCI settings

- .gitignore
- docs/index.md
This pull request fixes #607 by updating the guide to be clearer for new users.
> #607 Update docs for new users

- docs/_posts/2020-10-19-v4.8.1.md
- package.json
We're going to release a new patch version including #609 soon.
> version 4.8.1

- docs/_layouts/default.html
Fix dead or broken links in this docs page, making navigation easy for others.
> Fix broken url in docs
